name: freight-backend
services:
  web:
    container_name: freight-backend
    build: .
    ports:
      - "8080:8080"
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/freight
      - DB_USER=freight
      - DB_PASSWORD=freight
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: freight-db
    image: postgres:15.3-alpine
    ports:
      - "15432:5432"
    volumes:
      #- "./db_data/init:/docker-entrypoint-initdb.d"
      - "postgres_db:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: freight
      POSTGRES_PASSWORD: freight
      POSTGRES_DB: freight
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
volumes:
  postgres_db: