openapi: 3.1.0
info:
  title: Freight API
  description: Freight API
  version: latest
externalDocs:
  url: /
servers:
- url: http://localhost:8080
  description: Development Server
tags: []
paths:
  /api/auth/login:
    post:
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  title: String
                password:
                  type: string
                  title: String
              required:
              - password
              - username
              title: LoginCredential
        required: false
      responses:
        default:
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    title: Boolean
                  message:
                    type: string
                    title: String
                required:
                - message
                - ok
                title: Error
        "200":
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    title: Boolean
                  data:
                    $ref: "#/components/schemas/io.github.nitkc_proken.freight.backend.auth.UserWithTokenResponse"
                required:
                - data
                - ok
                title: Success
      deprecated: false
  /api/auth/logout:
    post:
      tags: []
      parameters: []
      responses:
        default:
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    title: Boolean
                  message:
                    type: string
                    title: String
                required:
                - message
                - ok
                title: Error
        "200":
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    title: Boolean
                  data:
                    type: "null"
                    title: Unit
                required:
                - ok
                title: Success
      deprecated: false
      security:
      - AppDefaultSecurityScheme: []
  /api/users/me:
    get:
      tags: []
      parameters: []
      responses:
        default:
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    title: Boolean
                  message:
                    type: string
                    title: String
                required:
                - message
                - ok
                title: Error
        "200":
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    title: Boolean
                  data:
                    $ref: "#/components/schemas/io.github.nitkc_proken.freight.backend.users.UserResponse"
                required:
                - data
                - ok
                title: Success
      deprecated: false
      security:
      - AppDefaultSecurityScheme: []
components:
  schemas:
    io.github.nitkc_proken.freight.backend.auth.UserWithTokenResponse:
      type: object
      properties:
        userId:
          type: string
          format: uuid
          title: Uuid
        username:
          type: string
          title: String
        token:
          $ref: "#/components/schemas/io.github.nitkc_proken.freight.backend.repository.Token"
      required:
      - token
      - userId
      - username
      title: UserWithTokenResponse
    io.github.nitkc_proken.freight.backend.repository.Token:
      type: object
      properties:
        token:
          type: string
          title: String
        expiresAt:
          type: string
          format: timestamp
          title: String#instant
      required:
      - expiresAt
      - token
      title: Token
    io.github.nitkc_proken.freight.backend.users.UserResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          title: Uuid
        username:
          type: string
          title: String
      required:
      - id
      - username
      title: UserResponse
  examples: {}
  securitySchemes:
    AppDefaultSecurityScheme:
      type: http
      scheme: bearer
